## Nonlinear Model Predicitive Control Parameters
chain_base_link: world
chain_tip_link: arm_7_link
root_frame: world

nmpc:
  state_dim: 7
  control_dim: 7
  time_horizon: 0.3
  shooting_nodes: 3
  
  base:
    base_active: false

  constraints:
    state:
      path_constraints:
        min: [-4.712, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [4.712,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
      terminal_constraints:
        min: [-4.712, -1.92, -2.967, -2.618, -2.967, -2.443, -2.967]
        max: [4.712,  1.92,  2.967,  2.618,  2.967,  2.443,  2.967]
    input:
      input_constraints:
        min: [ -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5]
        max: [  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5]
    min_distance: 0.15

